#!/bin/bash

EXTPKGSFOLDER="$SIMONPIFOLDER/$MODEL/pkgs"

presetsGen() {
	echo -e "[$G+$RST] Adding needed changes for emulation into $FILENAME ..."

	if [[ $MODEL == rpi ]]; then
		# It allows qemu virtualization and scsi functionality
		cat <<'EOF' > $ROOTPATH/etc/udev/rules.d/90-qemu.rules
KERNEL=="sda", SYMLINK+="mmcblk0"
KERNEL=="sda?", SYMLINK+="mmcblk0p%n"
KERNEL=="sda2", SYMLINK+="root"
EOF
	fi

	# Prevent vfat corruption for boot partition
	if [ -f $ROOTPATH/etc/fstab ]; then
		mv $ROOTPATH/etc/fstab $ROOTPATH/etc/fstab-off
	fi
	cat <<'EOF' > $ROOTPATH/etc/motd

        __                                                                        __
   ____/\_\    ___ ___                      ___     ___                    _____ /\_\
  /',__\/\ \ /' __` __`\      _______      / __`\ /' _ `\      _______    /\ '__`\/\ \
 /\__, `\ \ \/\ \/\ \/\ \    /\______\    /\ \L\ \/\ \/\ \    /\______\   \ \ \L\ \ \ \
 \/\____/\ \_\ \_\ \_\ \_\   \/______/    \ \____/\ \_\ \_\   \/______/    \ \ ,__/\ \_\
  \/___/  \/_/\/_/\/_/\/_/                 \/___/  \/_/\/_/                 \ \ \/  \/_/
                                                                             \ \_\
                                                                              \/_/
Written by Gianluca Boiano

In order to update the kernel image with pacman, you have to mount the boot partition.
Do not add entries for your boot partition to /etc/fstab unless you know what are you doing.

Remember to enable sshd on guest if you need it. Type:
systemctl enable sshd

To set tty lines type:
stty rows 28 columns 212
EOF

	# systemd-modules-load fix
	if [ -f $ROOTPATH/etc/modules-load.d/raspberrypi.conf ]; then
		mv $ROOTPATH/etc/modules-load.d/raspberrypi.conf \
		$ROOTPATH/etc/modules-load.d/raspberrypi-off
	fi
	sync
}

presetsDel() {
	echo -e "[$G+$RST] Removing needed changes for emulation from $FILENAME ..."

	if [[ $MODEL == rpi ]]; then
		rm $ROOTPATH/etc/udev/rules.d/90-qemu.rules
	fi
	if [ -f $ROOTPATH/etc/fstab-off ]; then
		mv $ROOTPATH/etc/fstab-off $ROOTPATH/etc/fstab
	fi
	if [ -f ROOTPATH/etc/motd ]; then
		rm $ROOTPATH/etc/motd
	fi
	if [ -f $ROOTPATH/etc/modules-load.d/raspberrypi-off ]; then
		mv $ROOTPATH/etc/modules-load.d/raspberrypi-off \
		$ROOTPATH/etc/modules-load.d/raspberrypi.conf
	fi
	sync
}

customContent() {
	if [ -d $EXTPKGSFOLDER ]; then
		echo -e "[$Y!$RST] $EXTPKGSFOLDER folder is present"
		if [ "$(ls $EXTPKGSFOLDER)" ]; then
			echo -e "[$Y!$RST] Copying custom content to $FILENAME ..."
			for i in $(ls $EXTPKGSFOLDER); do
				echo -e "	[$G+$RST] Copying $i in /home/alarm ..."
				cp $EXTPKGSFOLDER/$i $ROOTPATH/home/alarm
				sync
			done
		else
			echo -e "[$Y!$RST] $EXTPKGSFOLDER is empty"
		fi
	else
		echo -e "[$Y!$RST] $EXTPKGSFOLDER folder not present. Creating ..."
		mkdir -p $EXTPKGSFOLDER
		echo -e "[$Y!$RST] You could add custom content on img copying it under $EXTPKGSFOLDER"
	fi
}
