#!/bin/bash

DOCKER=

checkDocker() {
	if [ -f /.dockerenv ]; then
		DOCKER=1
		echo -e "[$Y!$RST] In a Docker container ..."
	else
		DOCKER=0
		echo -e "[$Y!$RST] Out of a Docker container ..."
	fi
}
