#!/bin/sh

# Network Variables
BRIDGE=rasp-br0
TAP=rasp-tap0
GATEWAY=192.168.66.1
FIRSTIP="${GATEWAY%.1}.2"
LASTIP="${GATEWAY%.1}.254"
BROADCAST="${GATEWAY%.1}.255"
NET="${GATEWAY%.1}.0"

# PID for dnsmasq dhcp server
DNSMASQPID=$(ps -ef | grep $GATEWAY | awk '/[d]nsmasq/{print $2}')

generateMAC() {
	# Generate Random MAC ADDRESS to avoid collisions
	printf -v MACADDR "52:54:%02x:%02x:%02x:%02x" $(( $RANDOM & 0xff)) $(( $RANDOM & 0xff )) $(( $RANDOM & 0xff)) $(( $RANDOM & 0xff ))
}

killNetwork() {
	echo -e "[$G+$RST] Shutting down present network for QEMU ..."

	if [ ! -z $DNSMASQPID ]; then
		sudo -E kill -9 "$DNSMASQPID"
	fi

	while [ -d "/sys/class/net/$BRIDGE" ] || [ -d "/sys/class/net/$TAP" ]; do
		sudo -E $IP link set "$TAP" nomaster > /dev/null 2>&1 # Enslave tap
		sudo -E $IP tuntap del dev "$TAP" mode tap > /dev/null  2>&1 # Remove tap
		sudo -E $IP link delete "$BRIDGE" type bridge > /dev/null 2>&1 # Remove bridge
		sudo -E sysctl -w net.ipv4.ip_forward=0 > /dev/null
	done
}

createNetwork() {
	echo -e "[$G+$RST] Turning up a network for QEMU ..."
	sudo -E sysctl -w net.ipv4.ip_forward=1 > /dev/null
	sudo -E $IP link add "$BRIDGE" type bridge # add bridge
	sudo -E $IP addr add "$GATEWAY"/24 broadcast "$BROADCAST" dev "$BRIDGE" # Set ip to bridge interface
	sudo -E $IP tuntap add dev "$TAP" mode tap # Add tap interface
	sudo -E $IP link set $TAP master "$BRIDGE" # Bind tap to bridge
	sudo -E $IP link set "$BRIDGE" up
	sudo -E $IP link set "$TAP" up promisc on
	sudo -E $DNSMASQ --listen-address="$GATEWAY" --interface="$BRIDGE" --bind-interfaces --dhcp-range="$FIRSTIP","$LASTIP"
	sudo -E $IPTABLES -t nat -I POSTROUTING -s "$NET"/24 -j MASQUERADE # Nat configuration
	echo -e "[$Y!$RST] Gateway address: $G$GATEWAY$RST"
}
