#!/bin/sh

. $OPT/simonpiemu/network

KERNELRPI=4.4.50
KERNELRPI2=4.9.59

# QEMU Variables
export QEMU_AUDIO_DRV=none

checkQemu() {
	if [ ! -z "$(pidof $QEMUARM)" ]; then
		pkill "$QEMUARM"
	fi
}

run_rpi() {
	checkQemu
	checkNetwork
	$QEMUARM -nographic \
		-cpu arm1176 \
		-m 256 \
		-M versatilepb \
		-drive file=$SIMONPIFOLDER/sd-arch-$MODEL-qemu.img,format=raw \
		-kernel $OPT/simonpiemu/qemu-kernel-$KERNELRPI \
		-append "root=/dev/sda2 rw console=ttyAMA0 loglevel=0 panic=1" \
		-no-reboot \
		-net nic,macaddr="$MACADDR" \
		-net tap,ifname="$TAP",script=no,downscript=no
		umountParts
	umountImg
}

run_rpi2() {
	checkQemu
	checkNetwork
	$QEMUARM -nographic \
		-cpu cortex-a15 \
		-m 1024 \
		-M vexpress-a15 \
		-sd $SIMONPIFOLDER/sd-arch-$MODEL-qemu.img \
		-kernel $OPT/simonpiemu/qemu-kernel-$KERNELRPI2 \
		-append "root=/dev/mmcblk0p2 rw console=ttyAMA0 loglevel=0 panic=1" \
		-dtb $OPT/simonpiemu/vexpress-v2p-ca15-tc1.dtb \
		-no-reboot \
		-net nic,macaddr="$MACADDR" \
		-net tap,ifname="$TAP",script=no,downscript=no
	umountParts
	umountImg
}

# Not working AArch64
run_rpi3() {
	checkQemu
	checkNetwork
	$QEMUARM64 -nographic \
		-m 512 \
		-M vexpress-a15 \
		-sd $SIMONPIFOLDER/sd-arch-$MODEL-qemu.img \
		-kernel $OPT/simonpiemu/qemu-kernel-$KERNELRPI2 \
		-append "root=/dev/mmcblk0p2 rw console=ttyAMA0 panic=1" \
		-dtb $OPT/simonpiemu/vexpress-v2p-ca15-tc1.dtb \
		-no-reboot \
		-net nic,macaddr="$MACADDR" \
		-net tap,ifname="$TAP",script=no,downscript=no
	umountParts
	umountImg
}

run_emu() {
	case $MODEL in
		rpi    ) run_rpi ;;
		rpi-2  ) run_rpi2 ;;
		rpi-3  ) run_rpi3 ;;
	esac
}
