#!/bin/bash

# Enable this for debug purpose only
#set -x

OPT=.

# You could overwrite paths using VARNAME=value ./simonpi

# Software used in this script.
AWK="awk"
BSDTAR="bsdtar"
DNSMASQ="dnsmasq"
EXT4="mkfs.ext4"
EXT4CHK="fsck.ext4"
FDISK="fdisk"
FILE="file"
GREP="grep"
IP="ip"
IPTABLES="iptables"
PS="ps"
QEMUARM="qemu-system-arm"
QEMUARM64="qemu-system-aarch64"
SUDO="sudo"
VFAT="mkfs.vfat"
VFATCHK="fsck.vfat"
WGET="wget"
PROGS=("$AWK" "$BSDTAR" "$DNSMASQ" "$EXT4" "$FDISK" "$FILE" "$GREP" "$IPTABLES" \
	"$PS" "$QEMUARM" "$QEMUARM64" "$SUDO" "$VFAT" "$WGET")

# Parameters, Folders and Files
VERSION=1.0.6
USER=$(whoami)
SNDARG=$2
GIGA=$3
MODEL=$1
IMGPATH=$3
SIMONPIFOLDER=~/.simonpi
FILENAME="sd-arch-$MODEL-qemu.img"
ARCHIMGPATH=$SIMONPIFOLDER/$FILENAME

# Importing external scripts
. $OPT/simonpiemu/scripts/checks
. $OPT/simonpiemu/scripts/docker
. $OPT/simonpiemu/scripts/storage
. $OPT/simonpiemu/scripts/custom
. $OPT/simonpiemu/scripts/images
. $OPT/simonpiemu/scripts/network
. $OPT/simonpiemu/scripts/qemu
. $OPT/simonpiemu/scripts/runemu

# Text Colors
FAIL='\e[0;31mFAILED\e[0m'
PASS='\e[0;32m  OK  \e[0m'
WARN='\e[0;33m WARN \e[0m'
G='\e[0;32m'
RST='\e[0m'

checkModel() {
	if [[ $MODEL != rpi* ]]; then
		echo "Please select the rpi model"
		echo "Available:	rpi	rpi-2	rpi-3"
		exit 1
	fi
}

checkDeps() {
	for i in "${PROGS[@]}"; do
		if which "$i" > /dev/null; then
			echo -e "[$PASS] $i executable found"
		else
			echo -e "[$FAIL] $i executable not found. Please install it on your distro"
			exit 1;
		fi
	done
}

version() {
	echo -e "$G$(cat < $OPT/simonpiemu/assets/motd | head -n 9)$RST"
	echo "v$VERSION"
	cat < $OPT/simonpiemu/assets/motd | tail -n -10 | head -n 1
	exit 0
}

help () {
	echo "A Swiss Army knife to emulate Raspberry PI family devices on your laptop."
	echo ""
	echo -e "Default storage is in $G$SIMONPIFOLDER$RST"
	echo ""
	echo "usage: ./simonpi MODEL [<opts>]"
	echo "	Available MODELs:	rpi	rpi-2	rpi-3"
	echo "	<opts>	-h			print this message"
	echo "		-c			check filesystem integrity of disk image"
	echo "		-e			purge everything in storage folder"
	echo "		-k			kill every instance and network virtual interface"
	echo "		-i	<path/to/img>	Run a custom disk image like Raspbian one"
	echo "		-l			list files in storage folder"
	echo "		-m			mount only loop devices ($DEVICE1, $DEVICE2)"
	echo "		-p			purge everything except for downloaded archives"
	echo "		-r			run QEMU processor emulator for defined model"
	echo "		-s	<size in GB>	write a partitioned raw image disk with Arch Linux"
	echo "		-u			unmount ${MOUNTFOLDERS[0]} and ${MOUNTFOLDERS[1]} folders"
	echo "examples:"
	echo "	./simonpi rpi-3 -s 2		create a 2GB sd .img for rpi-3"
	echo "	./simonpi rpi-2 -p		purge everything related to rpi-2 img creation"
	exit 0
}

process_args () {
	# Process other arguments.
	case "$1" in
		rpi   ) checkModel ;;
		rpi-2 ) checkModel ;;
		rpi-3 ) checkModel ;;
		-h    ) help ;;
		-v    ) version ;;
		*     ) checkModel ;;
	esac

	case "$2" in
		-c	  ) isMounted && checkMount && checkFs ;;
		-e	  ) isMounted && checkMount && purge && purgeEverything ;;
		-i    ) runCustomImg && isMounted && checkMount && presetsGen && run_emu ;;
		-k	  ) checkQemu && killQemu && fkillNetwork ;;
		-l	  ) listStorage ;;
		-m	  ) isMounted && checkMount ;;
		-p	  ) isMounted && checkMount && purge ;;
		-r    ) isMounted && checkMount && presetsGen && run_emu ;;
		-s    ) createArchImg ;;
		-u    ) isMounted && checkMount ;;
 		*    ) help ;;
	esac
}

process_args "$@";
