#!/bin/bash

ARCH=
GUESTPORT0=22
EXTERPORT0=2222
GUESTPORT1=80
EXTERPORT1=8080

# Must be root for some ops
checkRoot() {
	if [[ $(sudo whoami) != "root" ]]; then
		echo -e "[$FAIL] Sim-on-Pi will not continue"
		echo -e "[$FAIL] Please type your user password or run this script as root"
		exit 1
	fi
}

checkUser() {
	whoami
}

checkArch() {
	case $MODEL in
		rpi) ARCH="armv6h" ;;
		rpi-2) ARCH="armv7h" ;;
		rpi-3) ARCH="aarch64" ;;
	esac
}

finalizeIt() {
	umountParts
	umountImg
	checkQemu
	if [ "$DOCKER" = "0" ] && [ "$QEMUISRUNNING" = "0" ]; then
		killNetwork
	fi
}

initChecks() {
	checkDocker

	if [ "$DOCKER" = "0" ]; then
		checkRoot
		checkTap
		createNetwork

		if [ "$MODEL" = "rpi" ]; then
			NETWORKCMD=" -net nic,macaddr=$(genMAC) -net tap,ifname=$TAP,script=no,downscript=no"
		else
			NETWORKCMD=" -device virtio-net-device,mac=$(genMAC),netdev=net0 -netdev tap,id=net0,ifname=$TAP,script=no,downscript=no"
		fi

	else

		if [ "$MODEL" = "rpi" ]; then
			NETWORKCMD=" -net nic,macaddr=$(genMAC) -net user,hostfwd=tcp::$EXTERPORT0-:$GUESTPORT0,hostfwd=tcp::$EXTERPORT1-:$GUESTPORT1"
		else
			NETWORKCMD=" -device virtio-net-device,mac=$(genMAC),netdev=net0 -netdev user,id=net0,hostfwd=tcp::$EXTERPORT0-:$GUESTPORT0,hostfwd=tcp::$EXTERPORT1-:$GUESTPORT1"
		fi
	
	fi
}
