#!/bin/bash

# Must be root for some ops
checkRoot() {
	if [[ $(sudo whoami) != "root" ]]; then
		echo -e "[$FAIL] Sim-on-Pi will not continue"
		echo -e "[$FAIL] Please type your user password or run this script as root"
		exit 1
	fi
}

finalizeIt() {
	presetsDel
	umountParts
	umountImg

	if [ $DOCKER = "0" ]; then
		killNetwork
	fi
}

initChecks() {
	checkDocker
	if [ $DOCKER = "0" ]; then
		checkRoot
		checkTap
		createNetwork
		generateMAC
		NETWORKCMD=" -net nic,macaddr=$MACADDR -net tap,ifname=$TAP,script=no,downscript=no"
	else
		generateMAC
		NETWORKCMD=" -net nic,macaddr=$MACADDR -net user,hostfwd=tcp::2222-:22"
	fi
}
