#!/bin/bash

ARCH=
GUESTPORT0=22
EXTERPORT0=2222
GUESTPORT1=80
EXTERPORT1=8080

# Must be root for some ops
checkRoot() {
	if [[ $(sudo whoami) != "root" ]]; then
		echo -e "[$FAIL] Sim-on-Pi will not continue"
		echo -e "[$FAIL] Please type your user password or run this script as root"
		exit 1
	fi
}

checkArch() {
	case $MODEL in
		rpi) ARCH="armv6h" ;;
		rpi-2) ARCH="armv7h" ;;
		rpi-3) ARCH="aarch64" ;;
	esac
}

finalizeIt() {
	presetsDel
	umountParts
	umountImg
	checkQemu
	if [ "$DOCKER" = "0" ] && [ "$QEMUISRUNNING" = "0" ]; then
		killNetwork
	fi
}

initChecks() {
	checkDocker

	if [ "$DOCKER" = "0" ]; then
		checkRoot
		checkTap
		createNetwork
		NETWORKCMD=" -net nic,macaddr=$(genMAC) -net tap,ifname=$TAP,script=no,downscript=no"
	else
		NETWORKCMD=" -net nic,macaddr=$(genMAC) -net user,hostfwd=tcp::$EXTERPORT0-:$GUESTPORT0,hostfwd=tcp::$EXTERPORT1-:$GUESTPORT1"
	fi
}
