#!/bin/bash

CUSTOMDATAFOLDER="$SIMONPIFOLDER/$MODEL/data"
EXTPKGSFOLDER="$SIMONPIFOLDER/$MODEL/pkgs"

presetsGen() {
	echo -e "[$PASS] Adding needed changes for emulation into ${ARCHIMGPATH##*/} ..."
	checkRoot

	if [[ $MODEL == rpi ]]; then
		# It allows qemu virtualization and scsi functionality
		sudo -E cp "$OPT/simonpiemu/assets/90-qemu.rules" \
			"$ROOTPATH/etc/udev/rules.d/90-qemu.rules"
	fi

	# Prevent vfat corruption for boot partition
	if [ -f "$ROOTPATH/etc/fstab" ]; then
		sudo -E mv "$ROOTPATH/etc/fstab" "$ROOTPATH/etc/fstab-off"
		sudo -E cp "$OPT/simonpiemu/assets/fstab" "$ROOTPATH/etc/fstab"
	fi

	sudo -E cp "$OPT/simonpiemu/assets/motd" "$ROOTPATH/etc/motd"

	# systemd-modules-load fix
	if [ -f "$ROOTPATH/etc/modules-load.d/raspberrypi.conf" ]; then
		sudo -E mv "$ROOTPATH/etc/modules-load.d/raspberrypi.conf" \
			"$ROOTPATH/etc/modules-load.d/raspberrypi-off"
	fi

	sync
}

presetsDel() {
	echo -e "[$PASS] Removing needed changes for emulation from ${ARCHIMGPATH##*/} ..."
	if [[ $MODEL == rpi ]]; then
		sudo -E rm "$ROOTPATH/etc/udev/rules.d/90-qemu.rules"
	fi

	if [ -f "$ROOTPATH/etc/fstab-off" ]; then
		sudo -E mv "$ROOTPATH/etc/fstab-off" "$ROOTPATH/etc/fstab"
	fi

	if [ -f "$ROOTPATH/etc/motd" ]; then
		sudo -E rm "$ROOTPATH/etc/motd"
	fi

	if [ -f "$ROOTPATH/etc/modules-load.d/raspberrypi-off" ]; then
		sudo -E mv "$ROOTPATH/etc/modules-load.d/raspberrypi-off" \
			"$ROOTPATH/etc/modules-load.d/raspberrypi.conf"
	fi

	sync
}

customContent() {
	if [ -d "$CUSTOMDATAFOLDER" ]; then
		echo -e "[$WARN] $CUSTOMDATAFOLDER folder is present"
		if [ "$(ls "$CUSTOMDATAFOLDER")" ]; then
			echo -e "[$WARN] Copying custom content to ${ARCHIMGPATH##*/} ..."
			for i in $CUSTOMDATAFOLDER/*; do
				echo -e "	[$PASS] Copying ${i##*/} in /home/alarm ..."
				sudo -E cp "$i" "$ROOTPATH/home/alarm"
				sync
			done
		else
			echo -e "[$WARN] $CUSTOMDATAFOLDER is empty"
		fi
	else
		echo -e "[$WARN] $CUSTOMDATAFOLDER folder not present. Creating ..."
		mkdir -p "$CUSTOMDATAFOLDER"
		echo -e "[$WARN] You could add custom content on img copying it under $CUSTOMDATAFOLDER"
	fi

	if [ -d "$EXTPKGSFOLDER" ]; then
		echo -e "[$WARN] $EXTPKGSFOLDER folder is present"
		if [ "$(ls "$EXTPKGSFOLDER")" ]; then
			echo -e "[$WARN] Installing packages on ${ARCHIMGPATH##*/} ..."
			for i in $EXTPKGSFOLDER/*; do
				echo -e "	[$PASS] Installing ${i##*/} with pacman ..."
				checkArch
				sudo -E pacman --arch "$ARCH" -U "$i"  --root "$ROOTPATH" \
					--dbpath "$ROOTPATH/var/lib/pacman" --noconfirm > /dev/null 2>&1
				sync
			done
		else
			echo -e "[$WARN] $EXTPKGSFOLDER is empty"
		fi
	else
		echo -e "[$WARN] $EXTPKGSFOLDER folder not present. Creating ..."
		mkdir -p "$EXTPKGSFOLDER"
		echo -e "[$WARN] Pacman compliant packages under $EXTPKGSFOLDER will be automatically installed"
	fi
}
