#!/bin/bash

QEMUISRUNNING=

# QEMU Vars
export QEMU_AUDIO_DRV=none

checkQemu() {
	if [ ! -z "$(pidof $QEMUARM)" ] || [ ! -z "$(pidof $QEMUARM64)" ]; then
		QEMUISRUNNING=1
	else
		QEMUISRUNNING=0
	fi
}

killQemu() {
	if [ $QEMUISRUNNING = "1" ]; then
		echo -e "[$PASS] Killing QEMU instance ..."
		if [ ! -z "$(pidof $QEMUARM)" ]; then
			kill -SIGTERM "$(pidof $QEMUARM)"
		else
			kill -SIGTERM "$(pidof $QEMUARM64)"
		fi	else
		echo -e "[$WARN] QEMU is not running ..."
	fi
}