#!/bin/bash

QEMUISRUNNING=

# QEMU Vars
export QEMU_AUDIO_DRV=none

checkQemu() {
	if [ ! -z "$(pidof $QEMUARM)" ] || [ ! -z "$(pidof $QEMUARM64)" ]; then
		QEMUISRUNNING=1
	else
		QEMUISRUNNING=0
	fi
}

killQemu() {
	if [ $QEMUISRUNNING = "1" ]; then
		echo -e "[$PASS] Killing QEMU instances ..."
		if [ ! -z "$(pidof $QEMUARM)" ]; then
			for i in $(pidof $QEMUARM); do
				kill -9 "$i"
			done
		else
			for i in $(pidof $QEMUARM64); do
				kill -9 "$i"
			done
		fi
	else
		echo -e "[$WARN] QEMU is not running ..."
	fi
}