#!/bin/bash

SIMONPIFOLDER=~/.simonpi
MOUNTFOLDERS=("boot" "root")
BOOTPATH="$SIMONPIFOLDER/$MODEL/${MOUNTFOLDERS[0]}"
ROOTPATH="$SIMONPIFOLDER/$MODEL/${MOUNTFOLDERS[1]}"
IMGMOUNTED=
PMOUNTED=
START1=
START2=
LENGHT1=
LENGHT2=

# Loopback devices
DEVICE1=/dev/loop0
DEVICE2=/dev/loop1

checkFolders() {
	for i in ${MOUNTFOLDERS[@]}; do
		if [ -d "$SIMONPIFOLDER/$MODEL/$i" ]; then
			echo -e "[$Y!$RST] $MODEL/$i folder is present"
		else
			echo -e "[$G+$RST] Creating $MODEL/$i folder ..."
			mkdir -p "$SIMONPIFOLDER/$MODEL/$i"
			chown -R $USER:$USER "$SIMONPIFOLDER/$MODEL/$i"
		fi
	done
}

checkFs() {
	echo -e "[$G+$RST] Checking partitions to prevent failures ..."
	sudo -E $VFATCHK -p $DEVICE1 > /dev/null 2>&1
	sudo -E $EXT4CHK -p $DEVICE2 > /dev/null 2>&1
}

checkMount() {
	if [ $SNDARG = "-c" ]; then
		if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
			checkRoot
			mapImg
			mountImg
		elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
			checkRoot
			return
		elif [ $PMOUNTED = "1" ]; then
			checkRoot
			umountParts
		else
			exit 1
		fi
	fi

	if [ $SNDARG = "-e" ] || [ $SNDARG = "-p" ]; then
		if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
			return
		elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
			checkRoot
			umountImg
		elif [ $PMOUNTED = "1" ]; then
			checkRoot
			umountParts
			umountImg
		fi
	fi

	if [ $SNDARG = "-m" ]; then
		if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
			checkRoot
			mapImg
			mountImg
			checkFs
			mountParts
		elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
			checkRoot
			checkFs
			mountParts
		elif [ $PMOUNTED = "1" ]; then
			return
		else
			exit 1
		fi
	fi

	if [ $SNDARG = "-r" ]; then
		if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
			checkRoot
			mapImg
			mountImg
			checkFs
			mountParts
		elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
			mountParts
		elif [ $PMOUNTED = "1" ]; then
			return
		else
			exit 1
		fi
	fi

	if [ $SNDARG = "-u" ]; then
		if [ $IMGMOUNTED = "0" ] && [ $PMOUNTED = "0" ]; then
			echo -e "[$G!$RST] $FILENAME disk image not mounted"
		elif [ $IMGMOUNTED = "1" ] && [ $PMOUNTED = "0" ]; then
			checkRoot
			umountImg
		elif [ $PMOUNTED = "1" ]; then
			checkRoot
			umountParts
			umountImg
		else
			exit 1
		fi
	fi
}

isMounted() {
	if [ ! -f $SIMONPIFOLDER/$FILENAME ]; then
		echo -e "[$Y!$RST] No sd image to use on QEMU. Perhaps you have purged $FILENAME"
		IMGMOUNTED=2
		PMOUNTED=2
	elif [[ $(mount | grep $BOOTPATH) ]]; then
		IMGMOUNTED=1
		PMOUNTED=1
	elif [[ ! $(mount | grep $BOOTPATH) ]] && [[ $(mount | grep $DEVICE1) ]]; then
		IMGMOUNTED=1
		PMOUNTED=0
	else
		IMGMOUNTED=0
		PMOUNTED=0
	fi
}

formatLoDevices() {
	echo -e "[$G+$RST] Creating partitions on disk image named $FILENAME ..."
	sudo -E $VFAT -n boot -F 32 $DEVICE1 > /dev/null 2>&1
	sudo -E $EXT4 -L rootfs $DEVICE2 > /dev/null 2>&1
	sync
}

mountParts() {
	checkFolders
	echo -e "[$G+$RST] Mounting partitions of $FILENAME ..."
	sudo -E mount $DEVICE1 "$BOOTPATH"
	sudo -E mount $DEVICE2 "$ROOTPATH"
}

umountParts() {
	echo -e "[$G+$RST] Umounting partitions of $FILENAME ..."
	mountpointloop1=$(grep $DEVICE1 /proc/mounts | cut -d ' ' -f 2)
	mountpointloop2=$(grep $DEVICE2 /proc/mounts | cut -d ' ' -f 2)
	mountpoints=("$mountpointloop1" "$mountpointloop2")

	for i in ${mountpoints[@]}; do
		sudo -E umount "$i"
	done
}

listStorage() {
	checkFolders
	echo -e "[$Y!$RST] Content of $SIMONPIFOLDER/$MODEL"
	ls $SIMONPIFOLDER/$MODEL
}

mapImg() {
	echo -e "[$G+$RST] Mapping lenghts of partitions ..."
	START1=$(fdisk -lo Start $SIMONPIFOLDER/$FILENAME | tail -n 2 | head -n -1)
	START2=$(fdisk -lo Start $SIMONPIFOLDER/$FILENAME | tail -n 1)
	LENGTH1=$(fdisk -lo Sectors $SIMONPIFOLDER/$FILENAME | tail -n 2 | head -n -1)
	LENGHT2=$(fdisk -lo Sectors $SIMONPIFOLDER/$FILENAME | tail -n 1)
}

mountImg() {
	echo -e "[$G+$RST] Mounting disk image named $FILENAME ..."
	sudo -E losetup -o $(( START1*512 )) --sizelimit $(( LENGHT1*512 )) \
	$DEVICE1 $SIMONPIFOLDER/$FILENAME > /dev/null 2>&1
	sudo -E losetup -o $(( START2*512 )) --sizelimit $(( LENGHT2*512 )) \
	$DEVICE2 $SIMONPIFOLDER/$FILENAME > /dev/null 2>&1
}

umountImg() {
	echo -e "[$G+$RST] Unmounting disk image named $FILENAME ..."
	sudo -E losetup -D
}

purge () {
	rm -rf $SIMONPIFOLDER/$FILENAME
	echo -e "[$G+$RST] Soft cleaning ..."
}

purgeEverything() {
	rm -rf $SIMONPIFOLDER/$MODEL/
	echo -e "[$G+$RST] Hard cleaning ..."
}
